# MUSICC - Multi User Scenario Catalogue for Connected and Autonomous Vehicles
# Copyright (C)2020 Connected Places Catapult
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: musicc-support@cp.catapult.org.uk
#          https://cp.catapult.org.uk/case-studies/musicc/'
#
# Generated by Django 2.2 on 2019-08-02 11:24

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('system_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('instance_prefix', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]{1}$', 'Only upper case alphabetic characters are allowed.')])),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='musiccscenario',
            name='instance_prefix',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='opendrive',
            name='instance_prefix',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='openscenario',
            name='instance_prefix',
            field=models.CharField(max_length=1),
        ),
    ]
